// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4LstiIt73u1EQ5Zv2pKfnUgMJPlQw-7U',
    appId: '1:906368259064:web:92c3fbe3bfc4ba79c23c0d',
    messagingSenderId: '906368259064',
    projectId: 'fir-database-b1eb7',
    authDomain: 'fir-database-b1eb7.firebaseapp.com',
    storageBucket: 'fir-database-b1eb7.appspot.com',
    measurementId: 'G-2YLR3KVJS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVC_7668inTetfZgozeiPmZgv_SwG6JQU',
    appId: '1:906368259064:android:8c6e1486df79b402c23c0d',
    messagingSenderId: '906368259064',
    projectId: 'fir-database-b1eb7',
    storageBucket: 'fir-database-b1eb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH-OvpzwJRXYbcqvqBaTT09SK08hICLfU',
    appId: '1:906368259064:ios:e6bd2df25882ff2ac23c0d',
    messagingSenderId: '906368259064',
    projectId: 'fir-database-b1eb7',
    storageBucket: 'fir-database-b1eb7.appspot.com',
    iosBundleId: 'com.example.tqabayaapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH-OvpzwJRXYbcqvqBaTT09SK08hICLfU',
    appId: '1:906368259064:ios:e6bd2df25882ff2ac23c0d',
    messagingSenderId: '906368259064',
    projectId: 'fir-database-b1eb7',
    storageBucket: 'fir-database-b1eb7.appspot.com',
    iosBundleId: 'com.example.tqabayaapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4LstiIt73u1EQ5Zv2pKfnUgMJPlQw-7U',
    appId: '1:906368259064:web:d0b7576738ca562cc23c0d',
    messagingSenderId: '906368259064',
    projectId: 'fir-database-b1eb7',
    authDomain: 'fir-database-b1eb7.firebaseapp.com',
    storageBucket: 'fir-database-b1eb7.appspot.com',
    measurementId: 'G-FPE8Q96X9F',
  );
}
